#### Imputing data from Alpaca

In [36]:
import pandas as pd
import os
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
from MCForecastTools import MCSimulation
from datetime import datetime

In [2]:
load_dotenv()

True

In [3]:
# Setting the variables for the Alpaca API and secret keys
alpaca_api_key = os.getenv('APCA_API_KEY_ID')
alpaca_api_secret_key = os.getenv('APCA_API_SECRET_KEY')

display(type(alpaca_api_key))
display(type(alpaca_api_secret_key))

# Create the Alpaca tradeapi.REST object
alpaca_api = tradeapi.REST(alpaca_api_key, alpaca_api_secret_key, api_version = "v2")

str

str

In [61]:
# Set start and end dates of 10 years back from your current date
timeframe="1D"
ten_years_ago = pd.Timestamp.now(tz="America/New_York").year-10
today=pd.Timestamp.now()
start_date= pd.Timestamp(today- pd.Timedelta(days=3650), tz="America/New_York").isoformat()
end_date = pd.Timestamp(today).isoformat()
# Set number of rows to 1000 to retrieve the maximum amount of rows
max_rows=1000

In [62]:

"""
Shopify (NYSE:SHOP)
Square (NYSE:SQ)
Chipotle (NYSE:CMG)
Ross (NASDAQ:ROST)
Crocs (NASDAQ:CROX)
Amazon (NASDAQ:AMZN)
BioCryst Pharma (NASDAQ:BCRX)
Moderna (NasdaqGS: MRNA)
"""

tickers=["SHOP","SQ","CMG","ROST","CROX","AMZN","BCRX","MRNA"]

In [63]:
historical_df=alpaca_api.get_barset(
    tickers,
    timeframe,
    start=start_date,
    end=end_date,
    limit=max_rows
    ).df

# Display both the first and last five rows of the DataFrame
historical_df.head()
historical_df.tail()

                              AMZN                                             \
                              open       high       low      close     volume
time
2021-11-08 00:00:00-05:00  3522.00  3579.0000  3487.860  3487.8900  2763443.0
2021-11-09 00:00:00-05:00  3515.75  3593.7700  3501.425  3577.6500  3802632.0
2021-11-10 00:00:00-05:00  3562.01  3605.4500  3463.090  3482.1067  3695442.0
2021-11-11 00:00:00-05:00  3514.74  3543.2400  3467.470  3472.4600  2086143.0
2021-11-12 00:00:00-05:00  3488.89  3540.7263  3447.050  3525.9700  2316171.0

                            BCRX                                      ...  \
                            open   high      low    close     volume  ...
time                                                                  ...
2021-11-08 00:00:00-05:00  12.31  12.49  12.0525  12.2129  2756505.0  ...
2021-11-09 00:00:00-05:00  12.27  12.98  12.2200  12.9500  2809872.0  ...
2021-11-10 00:00:00-05:00  12.84  13.27  12.6200  12.7400  3180421.0  ...
2021-11-11 00:00:00-05:00  12.73  12.90  12.3200  12.3600  1568068.0  ...
2021-11-12 00:00:00-05:00  12.34  12.41  12.1000  12.2600  1746063.0  ...

                              SHOP                                           \
                              open       high       low    close     volume
time
2021-11-08 00:00:00-05:00  1540.00  1564.3300  1522.001  1534.12   722962.0
2021-11-09 00:00:00-05:00  1541.39  1563.0511  1519.810  1556.21   532750.0
2021-11-10 00:00:00-05:00  1533.68  1544.8700  1470.000  1474.46   646012.0
2021-11-11 00:00:00-05:00  1500.50  1512.0000  1490.000  1490.95   508723.0
2021-11-12 00:00:00-05:00  1513.94  1674.7850  1510.010  1669.52  2768760.0

                               SQ
                             open      high       low   close     volume
time
2021-11-08 00:00:00-05:00  237.99  241.4200  234.1500  236.72  6699191.0
2021-11-09 00:00:00-05:00  238.40  240.9000  229.7172  230.79  6894402.0
2021-11-10 00:00:00-05:00  230.21  234.6899  225.2500  227.32  6555696.0
2021-11-11 00:00:00-05:00  231.01  231.2200  225.6500  226.52  4449770.0
2021-11-12 00:00:00-05:00  228.14  229.7600  226.5100  227.25  5168190.0

[5 rows x 40 columns]